- Add patch that unbreaks cdr_tds with FreeTDS 0.82. - Properly obsolete conference subpackage.

diff --git a/0010-Update-autoconf.patch b/0010-Update-autoconf.patch
--- a/0010-Update-autoconf.patch
+++ b/0010-Update-autoconf.patch
@@ -1,15 +1,15 @@
-From ae5eb1dfb045ceec41777baf095feb32779f64ab Mon Sep 17 00:00:00 2001
+From d8af2026b55ad1c056de5b136340b0e3757a669f Mon Sep 17 00:00:00 2001
 From: Jeffrey C. Ollie <jeff@ocjtech.us>
-Date: Wed, 14 May 2008 14:03:39 -0500
+Date: Wed, 2 Jul 2008 10:19:36 -0500
 Subject: [PATCH] Update autoconf.
 
 ---
- configure                        |  983 +++++++++++++++++++++++++++++++-------
- include/asterisk/autoconfig.h.in |   20 +-
- 2 files changed, 820 insertions(+), 183 deletions(-)
+ configure                        | 1094 +++++++++++++++++++++++++++++---------
+ include/asterisk/autoconfig.h.in |   23 +-
+ 2 files changed, 865 insertions(+), 252 deletions(-)
 
 diff --git a/configure b/configure
-index d72fa38..93c1024 100755
+index d72fa38..1dd6af6 100755
 --- a/configure
 +++ b/configure
 @@ -1,5 +1,5 @@
@@ -586,7 +586,8 @@ index d72fa38..93c1024 100755
 +echo "${ECHO_T}no" >&6; }
 +fi
 +
-+
+ 
+-if test "x${PBX_LUA}" != "x1" -a "${USE_LUA}" != "no"; then
 +fi
 +if test -z "$ac_cv_prog_PKGCONFIG"; then
 +  ac_ct_PKGCONFIG=$PKGCONFIG
@@ -656,8 +657,7 @@ index d72fa38..93c1024 100755
 +
 +fi
 +
- 
--if test "x${PBX_LUA}" != "x1" -a "${USE_LUA}" != "no"; then
++
 +if test "x${PBX_RADIUS}" != "x1" -a "${USE_RADIUS}" != "no"; then
     pbxlibdir=""
 -   # if --with-LUA=DIR has been specified, use it.
@@ -1113,7 +1113,201 @@ index d72fa38..93c1024 100755
  _ACEOF
  
        fi
-@@ -49918,6 +50410,126 @@ fi
+@@ -43914,18 +44406,18 @@ if test "x${PBX_FREETDS}" != "x1" -a "${USE_FREETDS}" != "no"; then
+       	 pbxlibdir="-L${FREETDS_DIR}"
+       fi
+    fi
+-   pbxfuncname="tds_version"
++   pbxfuncname="dbinit"
+    if test "x${pbxfuncname}" = "x" ; then   # empty lib, assume only headers
+       AST_FREETDS_FOUND=yes
+    else
+-      as_ac_Lib=`echo "ac_cv_lib_tds_${pbxfuncname}" | $as_tr_sh`
+-{ echo "$as_me:$LINENO: checking for ${pbxfuncname} in -ltds" >&5
+-echo $ECHO_N "checking for ${pbxfuncname} in -ltds... $ECHO_C" >&6; }
++      as_ac_Lib=`echo "ac_cv_lib_sybdb_${pbxfuncname}" | $as_tr_sh`
++{ echo "$as_me:$LINENO: checking for ${pbxfuncname} in -lsybdb" >&5
++echo $ECHO_N "checking for ${pbxfuncname} in -lsybdb... $ECHO_C" >&6; }
+ if { as_var=$as_ac_Lib; eval "test \"\${$as_var+set}\" = set"; }; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+-LIBS="-ltds ${pbxlibdir}  $LIBS"
++LIBS="-lsybdb ${pbxlibdir}  $LIBS"
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+@@ -43991,29 +44483,29 @@ fi
+ 
+    # now check for the header.
+    if test "${AST_FREETDS_FOUND}" = "yes"; then
+-      FREETDS_LIB="${pbxlibdir} -ltds "
++      FREETDS_LIB="${pbxlibdir} -lsybdb "
+       # if --with-FREETDS=DIR has been specified, use it.
+       if test "x${FREETDS_DIR}" != "x"; then
+ 	 FREETDS_INCLUDE="-I${FREETDS_DIR}/include"
+       fi
+       FREETDS_INCLUDE="${FREETDS_INCLUDE} "
+-      if test "xtds.h" = "x" ; then	# no header, assume found
++      if test "xsybdb.h" = "x" ; then	# no header, assume found
+          FREETDS_HEADER_FOUND="1"
+       else				# check for the header
+          saved_cppflags="${CPPFLAGS}"
+          CPPFLAGS="${CPPFLAGS} ${FREETDS_INCLUDE} "
+-	 if test "${ac_cv_header_tds_h+set}" = set; then
+-  { echo "$as_me:$LINENO: checking for tds.h" >&5
+-echo $ECHO_N "checking for tds.h... $ECHO_C" >&6; }
+-if test "${ac_cv_header_tds_h+set}" = set; then
++	 if test "${ac_cv_header_sybdb_h+set}" = set; then
++  { echo "$as_me:$LINENO: checking for sybdb.h" >&5
++echo $ECHO_N "checking for sybdb.h... $ECHO_C" >&6; }
++if test "${ac_cv_header_sybdb_h+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ fi
+-{ echo "$as_me:$LINENO: result: $ac_cv_header_tds_h" >&5
+-echo "${ECHO_T}$ac_cv_header_tds_h" >&6; }
++{ echo "$as_me:$LINENO: result: $ac_cv_header_sybdb_h" >&5
++echo "${ECHO_T}$ac_cv_header_sybdb_h" >&6; }
+ else
+   # Is the header compilable?
+-{ echo "$as_me:$LINENO: checking tds.h usability" >&5
+-echo $ECHO_N "checking tds.h usability... $ECHO_C" >&6; }
++{ echo "$as_me:$LINENO: checking sybdb.h usability" >&5
++echo $ECHO_N "checking sybdb.h usability... $ECHO_C" >&6; }
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+@@ -44021,7 +44513,7 @@ cat confdefs.h >>conftest.$ac_ext
+ cat >>conftest.$ac_ext <<_ACEOF
+ /* end confdefs.h.  */
+ $ac_includes_default
+-#include <tds.h>
++#include <sybdb.h>
+ _ACEOF
+ rm -f conftest.$ac_objext
+ if { (ac_try="$ac_compile"
+@@ -44053,15 +44545,15 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+ echo "${ECHO_T}$ac_header_compiler" >&6; }
+ 
+ # Is the header present?
+-{ echo "$as_me:$LINENO: checking tds.h presence" >&5
+-echo $ECHO_N "checking tds.h presence... $ECHO_C" >&6; }
++{ echo "$as_me:$LINENO: checking sybdb.h presence" >&5
++echo $ECHO_N "checking sybdb.h presence... $ECHO_C" >&6; }
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+ cat confdefs.h >>conftest.$ac_ext
+ cat >>conftest.$ac_ext <<_ACEOF
+ /* end confdefs.h.  */
+-#include <tds.h>
++#include <sybdb.h>
+ _ACEOF
+ if { (ac_try="$ac_cpp conftest.$ac_ext"
+ case "(($ac_try" in
+@@ -44094,25 +44586,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6; }
+ # So?  What about this header?
+ case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+   yes:no: )
+-    { echo "$as_me:$LINENO: WARNING: tds.h: accepted by the compiler, rejected by the preprocessor!" >&5
+-echo "$as_me: WARNING: tds.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: tds.h: proceeding with the compiler's result" >&5
+-echo "$as_me: WARNING: tds.h: proceeding with the compiler's result" >&2;}
++    { echo "$as_me:$LINENO: WARNING: sybdb.h: accepted by the compiler, rejected by the preprocessor!" >&5
++echo "$as_me: WARNING: sybdb.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
++    { echo "$as_me:$LINENO: WARNING: sybdb.h: proceeding with the compiler's result" >&5
++echo "$as_me: WARNING: sybdb.h: proceeding with the compiler's result" >&2;}
+     ac_header_preproc=yes
+     ;;
+   no:yes:* )
+-    { echo "$as_me:$LINENO: WARNING: tds.h: present but cannot be compiled" >&5
+-echo "$as_me: WARNING: tds.h: present but cannot be compiled" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: tds.h:     check for missing prerequisite headers?" >&5
+-echo "$as_me: WARNING: tds.h:     check for missing prerequisite headers?" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: tds.h: see the Autoconf documentation" >&5
+-echo "$as_me: WARNING: tds.h: see the Autoconf documentation" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: tds.h:     section \"Present But Cannot Be Compiled\"" >&5
+-echo "$as_me: WARNING: tds.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: tds.h: proceeding with the preprocessor's result" >&5
+-echo "$as_me: WARNING: tds.h: proceeding with the preprocessor's result" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: tds.h: in the future, the compiler will take precedence" >&5
+-echo "$as_me: WARNING: tds.h: in the future, the compiler will take precedence" >&2;}
++    { echo "$as_me:$LINENO: WARNING: sybdb.h: present but cannot be compiled" >&5
++echo "$as_me: WARNING: sybdb.h: present but cannot be compiled" >&2;}
++    { echo "$as_me:$LINENO: WARNING: sybdb.h:     check for missing prerequisite headers?" >&5
++echo "$as_me: WARNING: sybdb.h:     check for missing prerequisite headers?" >&2;}
++    { echo "$as_me:$LINENO: WARNING: sybdb.h: see the Autoconf documentation" >&5
++echo "$as_me: WARNING: sybdb.h: see the Autoconf documentation" >&2;}
++    { echo "$as_me:$LINENO: WARNING: sybdb.h:     section \"Present But Cannot Be Compiled\"" >&5
++echo "$as_me: WARNING: sybdb.h:     section \"Present But Cannot Be Compiled\"" >&2;}
++    { echo "$as_me:$LINENO: WARNING: sybdb.h: proceeding with the preprocessor's result" >&5
++echo "$as_me: WARNING: sybdb.h: proceeding with the preprocessor's result" >&2;}
++    { echo "$as_me:$LINENO: WARNING: sybdb.h: in the future, the compiler will take precedence" >&5
++echo "$as_me: WARNING: sybdb.h: in the future, the compiler will take precedence" >&2;}
+     ( cat <<\_ASBOX
+ ## ------------------------------- ##
+ ## Report this to www.asterisk.org ##
+@@ -44121,18 +44613,18 @@ _ASBOX
+      ) | sed "s/^/$as_me: WARNING:     /" >&2
+     ;;
+ esac
+-{ echo "$as_me:$LINENO: checking for tds.h" >&5
+-echo $ECHO_N "checking for tds.h... $ECHO_C" >&6; }
+-if test "${ac_cv_header_tds_h+set}" = set; then
++{ echo "$as_me:$LINENO: checking for sybdb.h" >&5
++echo $ECHO_N "checking for sybdb.h... $ECHO_C" >&6; }
++if test "${ac_cv_header_sybdb_h+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+-  ac_cv_header_tds_h=$ac_header_preproc
++  ac_cv_header_sybdb_h=$ac_header_preproc
+ fi
+-{ echo "$as_me:$LINENO: result: $ac_cv_header_tds_h" >&5
+-echo "${ECHO_T}$ac_cv_header_tds_h" >&6; }
++{ echo "$as_me:$LINENO: result: $ac_cv_header_sybdb_h" >&5
++echo "${ECHO_T}$ac_cv_header_sybdb_h" >&6; }
+ 
+ fi
+-if test $ac_cv_header_tds_h = yes; then
++if test $ac_cv_header_sybdb_h = yes; then
+   FREETDS_HEADER_FOUND=1
+ else
+   FREETDS_HEADER_FOUND=0
+@@ -44164,33 +44656,6 @@ _ACEOF
+    fi
+ fi
+ 
+-if test "${PBX_FREETDS}" != "0";
+-then
+-    if test "${FREETDS_DIR}x" = "x";
+-    then
+-        for tds_dir in /usr /usr/local;
+-        do
+-            if test -f "${tds_dir}/include/tdsver.h";
+-            then
+-                FREETDS_DIR="${tds_dir}"
+-            fi
+-        done
+-    fi
+-    case `${GREP} TDS_VERSION_NO ${FREETDS_DIR:-/usr}/include/tdsver.h` in
+-    *0.64*)
+-        FREETDS_INCLUDE="${FREETDS_INCLUDE} -DFREETDS_0_64"
+-	;;
+-    *0.63*)
+-        FREETDS_INCLUDE="${FREETDS_INCLUDE} -DFREETDS_0_63"
+-	;;
+-    *0.62*)
+-        FREETDS_INCLUDE="${FREETDS_INCLUDE} -DFREETDS_0_62"
+-	;;
+-    *)
+-        FREETDS_INCLUDE="${FREETDS_INCLUDE} -DFREETDS_PRE_0_62"
+-	;;
+-    esac
+-fi
+ 
+ 
+ if test "x${PBX_TERMCAP}" != "x1" -a "${USE_TERMCAP}" != "no"; then
+@@ -49918,6 +50383,126 @@ fi
  
  
  
@@ -1240,7 +1434,7 @@ index d72fa38..93c1024 100755
  if test "${USE_CURL}" != "no"; then
     if test -n "$ac_tool_prefix"; then
    # Extract the first word of "${ac_tool_prefix}curl-config", so it can be a program name with args.
-@@ -50892,14 +51504,18 @@ BKTR_LIB!$BKTR_LIB$ac_delim
+@@ -50892,14 +51477,18 @@ BKTR_LIB!$BKTR_LIB$ac_delim
  BKTR_INCLUDE!$BKTR_INCLUDE$ac_delim
  BKTR_DIR!$BKTR_DIR$ac_delim
  PBX_BKTR!$PBX_BKTR$ac_delim
@@ -1263,7 +1457,7 @@ index d72fa38..93c1024 100755
  CURSES_LIB!$CURSES_LIB$ac_delim
  CURSES_INCLUDE!$CURSES_INCLUDE$ac_delim
  CURSES_DIR!$CURSES_DIR$ac_delim
-@@ -50952,6 +51568,10 @@ LDAP_LIB!$LDAP_LIB$ac_delim
+@@ -50952,6 +51541,10 @@ LDAP_LIB!$LDAP_LIB$ac_delim
  LDAP_INCLUDE!$LDAP_INCLUDE$ac_delim
  LDAP_DIR!$LDAP_DIR$ac_delim
  PBX_LDAP!$PBX_LDAP$ac_delim
@@ -1274,7 +1468,7 @@ index d72fa38..93c1024 100755
  LTDL_LIB!$LTDL_LIB$ac_delim
  LTDL_INCLUDE!$LTDL_INCLUDE$ac_delim
  LTDL_DIR!$LTDL_DIR$ac_delim
-@@ -50969,14 +51589,6 @@ NBS_INCLUDE!$NBS_INCLUDE$ac_delim
+@@ -50969,14 +51562,6 @@ NBS_INCLUDE!$NBS_INCLUDE$ac_delim
  NBS_DIR!$NBS_DIR$ac_delim
  PBX_NBS!$PBX_NBS$ac_delim
  NCURSES_LIB!$NCURSES_LIB$ac_delim
@@ -1289,7 +1483,7 @@ index d72fa38..93c1024 100755
  _ACEOF
  
    if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
-@@ -51018,6 +51630,14 @@ _ACEOF
+@@ -51018,6 +51603,14 @@ _ACEOF
  ac_delim='%!_!# '
  for ac_last_try in false false false false false :; do
    cat >conf$$subs.sed <<_ACEOF
@@ -1304,7 +1498,7 @@ index d72fa38..93c1024 100755
  NEWT_INCLUDE!$NEWT_INCLUDE$ac_delim
  NEWT_DIR!$NEWT_DIR$ac_delim
  PBX_NEWT!$PBX_NEWT$ac_delim
-@@ -51077,6 +51697,10 @@ SDL_IMAGE_LIB!$SDL_IMAGE_LIB$ac_delim
+@@ -51077,6 +51670,10 @@ SDL_IMAGE_LIB!$SDL_IMAGE_LIB$ac_delim
  SDL_IMAGE_INCLUDE!$SDL_IMAGE_INCLUDE$ac_delim
  SDL_IMAGE_DIR!$SDL_IMAGE_DIR$ac_delim
  PBX_SDL_IMAGE!$PBX_SDL_IMAGE$ac_delim
@@ -1315,7 +1509,7 @@ index d72fa38..93c1024 100755
  SPEEX_LIB!$SPEEX_LIB$ac_delim
  SPEEX_INCLUDE!$SPEEX_INCLUDE$ac_delim
  SPEEX_DIR!$SPEEX_DIR$ac_delim
-@@ -51103,18 +51727,6 @@ OPENSSL_DIR!$OPENSSL_DIR$ac_delim
+@@ -51103,18 +51700,6 @@ OPENSSL_DIR!$OPENSSL_DIR$ac_delim
  PBX_OPENSSL!$PBX_OPENSSL$ac_delim
  FREETDS_LIB!$FREETDS_LIB$ac_delim
  FREETDS_INCLUDE!$FREETDS_INCLUDE$ac_delim
@@ -1334,7 +1528,7 @@ index d72fa38..93c1024 100755
  _ACEOF
  
    if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
-@@ -51156,6 +51768,18 @@ _ACEOF
+@@ -51156,6 +51741,18 @@ _ACEOF
  ac_delim='%!_!# '
  for ac_last_try in false false false false false :; do
    cat >conf$$subs.sed <<_ACEOF
@@ -1353,7 +1547,7 @@ index d72fa38..93c1024 100755
  TONEZONE_DIR!$TONEZONE_DIR$ac_delim
  PBX_TONEZONE!$PBX_TONEZONE$ac_delim
  USB_LIB!$USB_LIB$ac_delim
-@@ -51209,6 +51833,7 @@ OPENH323_INCDIR!$OPENH323_INCDIR$ac_delim
+@@ -51209,6 +51806,7 @@ OPENH323_INCDIR!$OPENH323_INCDIR$ac_delim
  OPENH323_LIBDIR!$OPENH323_LIBDIR$ac_delim
  OPENH323_SUFFIX!$OPENH323_SUFFIX$ac_delim
  OPENH323_BUILD!$OPENH323_BUILD$ac_delim
@@ -1361,7 +1555,7 @@ index d72fa38..93c1024 100755
  PBX_SPEEX_PREPROCESS!$PBX_SPEEX_PREPROCESS$ac_delim
  CONFIG_GMIME!$CONFIG_GMIME$ac_delim
  PBX_ZAPTEL_VLDTMF!$PBX_ZAPTEL_VLDTMF$ac_delim
-@@ -51222,12 +51847,12 @@ PBX_H323!$PBX_H323$ac_delim
+@@ -51222,12 +51820,12 @@ PBX_H323!$PBX_H323$ac_delim
  PBX_IXJUSER!$PBX_IXJUSER$ac_delim
  CONFIG_SDL!$CONFIG_SDL$ac_delim
  CONFIG_GTK!$CONFIG_GTK$ac_delim
@@ -1377,7 +1571,7 @@ index d72fa38..93c1024 100755
    elif $ac_last_try; then
      { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
 diff --git a/include/asterisk/autoconfig.h.in b/include/asterisk/autoconfig.h.in
-index b368c8d..07deb31 100644
+index 3a76722..07deb31 100644
 --- a/include/asterisk/autoconfig.h.in
 +++ b/include/asterisk/autoconfig.h.in
 @@ -116,6 +116,12 @@
@@ -1430,6 +1624,16 @@ index b368c8d..07deb31 100644
  /* Define this to indicate the ${SPEEX_DESCRIP} library */
  #undef HAVE_SPEEX
  
+@@ -1193,6 +1205,9 @@
+ #ifndef _POSIX_PTHREAD_SEMANTICS
+ # undef _POSIX_PTHREAD_SEMANTICS
+ #endif
++#ifndef _TANDEM_SOURCE
++# undef _TANDEM_SOURCE
++#endif
+ 
+ /* Define like PROTOTYPES; this can be used by system headers. */
+ #undef __PROTOTYPES
 -- 
-1.5.4.3
+1.5.5.2
 
